# 02 — Data Inspection
**Sprint 4: Data Inspection & Exploratory Data Analysis (EDA)**

Inspect the dataset's dimensions, columns, data types, index, sample records, descriptive statistics, unique values, and category frequencies. This notebook focuses on understanding the raw data—not performing full preprocessing.

## Setup — Load the dataset

### Concept
Before inspecting data, load the intended file and confirm that it loaded successfully. Pandas represents tabular data using a `DataFrame`.

### Example
A telecom analyst loads customer records before checking customer tenure, contract types, charges, and churn labels.

### Code

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path("../dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv")

# Also support running this notebook from the project root.
if not DATA_PATH.exists():
    alternative = Path("dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv")
    if alternative.exists():
        DATA_PATH = alternative

if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"CSV not found: {DATA_PATH.resolve()}. "
        "Download the dataset and update DATA_PATH."
    )

df = pd.read_csv(DATA_PATH)
print("Dataset loaded successfully.")
display(df.head())

Dataset loaded successfully.

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Output explanation
You should see the first few customer records. If the file is not found, check the filename and folder location.
Confirming the correct file was loaded prevents the rest of the analysis from being performed on an unintended dataset.

## 1. Number of Rows

### Concept
A row usually represents one observation. In this dataset, one row is intended to represent one customer record.

### Example
If there are 7,043 rows, the file contains 7,043 customer records; this does not automatically guarantee 7,043 unique customers.

### Code

In [2]:
print("Number of rows:", len(df))
print("Number of rows using shape:", df.shape[0])

Number of rows: 7043
Number of rows using shape: 7043

### Output explanation
Both expressions should return the same number because `len(df)` and `df.shape[0]` count DataFrame rows.
The row count is a baseline to compare against later checks for duplicates, missing target values, and any records that may require special attention.

## 2. Number of Columns

### Concept
Columns represent attributes or fields recorded for each observation.

### Example
A customer dataset may include tenure, contract type, monthly charges, and churn status.

### Code

In [3]:
print("Number of columns:", len(df.columns))
print("Column names:")
print(df.columns.to_list())

Number of columns: 21
Column names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

### Output explanation
The first line shows the number of columns; the list shows their exact names.
Column names help identify fields that may represent features, identifiers, or the target. Exact spelling matters when selecting columns in code.

## 3. Column Names

### Concept
Column names are labels used to reference fields. Clear names make analysis easier, but names alone do not fully explain a field's meaning.

### Example
`MonthlyCharges` suggests a recurring monthly charge, while `Churn` suggests whether the customer left.

### Code

In [4]:
for position, column in enumerate(df.columns, start=1):
    print(f"{position:02d}. {column}")

01. customerID
02. gender
03. SeniorCitizen
04. Partner
05. Dependents
06. tenure
07. PhoneService
08. MultipleLines
09. InternetService
10. OnlineSecurity
11. OnlineBackup
12. DeviceProtection
13. TechSupport
14. StreamingTV
15. StreamingMovies
16. Contract
17. PaperlessBilling
18. PaymentMethod
19. MonthlyCharges
20. TotalCharges
21. Churn

### Output explanation
Each column is displayed with its position in the dataset.
Use the source documentation to confirm definitions and units, especially for fields whose meaning is not obvious from the name.

## 4. Dataset Index

### Concept
A pandas index labels rows in a DataFrame. When reading a CSV without specifying an index column, pandas usually creates a default integer index starting at zero.

### Example
Index label `0` refers to the first row currently in the DataFrame. It is not necessarily a business identifier such as `customerID`.

### Code

In [5]:
print("Index object:", df.index)
print("First five index labels:", df.index[:5].to_list())
print("Is index unique?", df.index.is_unique)

Index object: RangeIndex(start=0, stop=7043, step=1)
First five index labels: [0, 1, 2, 3, 4]
Is index unique? True

### Output explanation
The output describes the DataFrame's row index, shows its first labels, and checks whether the index labels are unique.

### Insight
A unique default index does not prove that customer records are unique. Check business identifiers and duplicated rows separately.

## 5. `head()`

### Concept
`head(n)` returns the first `n` rows. It is useful for a quick preview of the dataset.

### Example
An analyst checks the first five records after importing a CSV.

### Code

In [6]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Output explanation
The first five rows are displayed by default.
Look for readable column names, plausible values, unexpected blank fields, and whether the table appears to have parsed correctly.

## 6. `tail()`

### Concept
`tail(n)` returns the last `n` rows. It can help reveal issues near the end of a file that a first-row preview might miss.

### Example
Check the last five records to see whether the file ends with valid data rows.

### Code

In [8]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

### Output explanation
The last five rows are displayed by default.
Compare the beginning and end of the file for unusual formatting or unexpected records. This is only a quick visual check, not a complete validation.

## 7. `sample()`

### Concept
`sample(n)` selects a random sample of rows. It can give a quick view of records from different parts of the dataset.

### Example
A reviewer inspects five randomly selected customers rather than only the first or last records.

### Code

In [9]:
df.sample(n=min(5, len(df)), random_state=42)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.8,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.7,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.1,No

### Output explanation
Up to five rows are displayed. `random_state=42` makes the selected sample reproducible when the data is unchanged.
Random sampling can reveal values not seen in `head()` or `tail()`, but a small sample cannot establish that the entire dataset is clean.

## 8. `shape`

### Concept
The `shape` attribute returns a tuple: `(number_of_rows, number_of_columns)`.

### Example
A shape of `(7043, 21)` means 7,043 rows and 21 columns. Your actual result depends on the file you use.

### Code

In [10]:
print("Shape:", df.shape)
rows, columns = df.shape
print(f"{rows:,} rows × {columns} columns")

Shape: (7043, 21)
7,043 rows × 21 columns

### Output explanation
The tuple gives rows first and columns second.
Use this as a compact baseline for documenting dataset size and verifying that the expected file was loaded.

## 9. `info()`

### Concept
`info()` prints a structural summary, including column names, non-null counts, data types, and memory usage.

### Example
A charge field may appear as `object` instead of a numeric type if it contains blank strings or other text.

### Code

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

### Output explanation
For each column, compare its non-null count with the total number of rows. The dtype column indicates how pandas currently stores values.
A lower non-null count can indicate missing values recognized by pandas. However, empty strings and placeholders may not count as missing until investigated. A numeric-looking text column also needs attention.

## 10. `describe()`

### Concept
`describe()` summarizes data using statistics. By default, it summarizes numerical columns with count, mean, standard deviation, minimum, quartiles, and maximum.

### Example
For `MonthlyCharges`, the summary can show the typical charge, spread, and range.

### Code

In [12]:
display(df.describe())

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

### Output explanation
- `count`: non-missing numeric values
- `mean`: arithmetic average
- `std`: standard deviation
- `min` and `max`: smallest and largest values
- `25%`, `50%`, `75%`: quartiles; the 50th percentile is the median

Unexpected minima, maxima, or large gaps between the mean and median may warrant further inspection. Summary statistics do not explain why a value is unusual.

## 11. `dtypes`

### Concept
The `dtypes` attribute shows the pandas data type assigned to each column.

### Example
A column stored as `object` might contain category labels, identifiers, or numbers stored as text.

### Code

In [13]:
display(df.dtypes.to_frame(name="data_type"))

                 data_type
customerID             str
gender                 str
SeniorCitizen        int64
Partner                str
Dependents             str
tenure               int64
PhoneService           str
MultipleLines          str
InternetService        str
OnlineSecurity         str
OnlineBackup           str
DeviceProtection       str
TechSupport            str
StreamingTV            str
StreamingMovies        str
Contract               str
PaperlessBilling       str
PaymentMethod          str
MonthlyCharges     float64
TotalCharges           str
Churn                  str

### Output explanation
Each column is paired with its current pandas dtype, such as `int64`, `float64`, or `object`.
Dtypes describe storage, not necessarily business meaning. For example, `SeniorCitizen` may be stored as an integer but represent a binary category.

## 12. `nunique()`

### Concept
`nunique()` counts distinct values in each column. By default, missing values are excluded.

### Example
A column with two unique non-missing values may be binary, while a customer ID may have nearly as many unique values as rows.

### Code

In [14]:
unique_counts = df.nunique()
display(unique_counts.to_frame(name="unique_non_missing_values").sort_values(
    "unique_non_missing_values", ascending=False
))

                  unique_non_missing_values
customerID                             7043
TotalCharges                           6531
MonthlyCharges                         1585
tenure                                   73
PaymentMethod                             4
StreamingMovies                           3
TechSupport                               3
OnlineBackup                              3
StreamingTV                               3
DeviceProtection                          3
MultipleLines                             3
InternetService                           3
OnlineSecurity                            3
Contract                                  3
Partner                                   2
SeniorCitizen                             2
gender                                    2
Dependents                                2
PhoneService                              2
PaperlessBilling                          2
Churn                                     2

### Output explanation
The table ranks columns by the number of distinct non-missing values.
High cardinality may indicate an identifier or a field with many distinct values. Low cardinality may indicate a binary or categorical feature. Always confirm using column meaning.

## 13. `value_counts()`

### Concept
`value_counts()` counts how often each value appears in a Series. It is especially useful for categorical columns and target labels.

### Example
Counting `Contract` values can show whether month-to-month contracts are more common than one-year or two-year contracts.

### Code

In [16]:
for column in ["Contract", "InternetService", "PaymentMethod", "Churn"]:
    if column in df.columns:
        print(f"\nValue counts for {column}:")
        display(df[column].value_counts(dropna=False).to_frame("count"))

Value counts for Contract:

                count
Contract
Month-to-month   3875
Two year         1695
One year         1473

Value counts for InternetService:

                 count
InternetService
Fiber optic       3096
DSL               2421
No                1526

Value counts for PaymentMethod:

                           count
PaymentMethod
Electronic check            2365
Mailed check                1612
Bank transfer (automatic)   1544
Credit card (automatic)     1522

Value counts for Churn:

       count
Churn
No      5174
Yes     1869

### Output explanation
Each table lists observed values and their counts. `dropna=False` includes missing values if pandas recognizes any.
Counts can reveal dominant categories, rare categories, unexpected labels, and possible class imbalance. Later notebooks will explore these patterns more deeply.

## 14. Identify Column Roles

### Concept
Before deeper EDA, classify columns by their likely role: numerical, categorical/text, date/time, identifier, or potential target. This classification is a starting point and should be verified against business definitions.

### Example
`customerID` is a likely identifier; `Churn` is the target; `MonthlyCharges` is a numerical measurement; `Contract` is categorical.

### Code

In [21]:

numeric_columns = df.select_dtypes(include=np.number).columns.to_list()

categorical_columns = df.select_dtypes(
    include=["object", "str", "category"]
).columns.to_list()

datetime_columns = df.select_dtypes(
    include=["datetime", "datetimetz"]
).columns.to_list()

identifier_columns = [
    col for col in df.columns
    if col.lower() in {"customerid", "customer_id", "id", "record_id"}
    or col.lower().endswith("_id")
]

potential_target_columns = [
    col for col in [
        "Churn", "Exited", "Attrition",
        "target", "Target", "label"
    ]
    if col in df.columns
]

print("Numerical dtype columns:", numeric_columns)
print("\nCategorical/text dtype columns:", categorical_columns)
print("\nDate/time dtype columns:", datetime_columns)
print("\nPotential identifier columns:", identifier_columns)
print("\nPotential target columns:", potential_target_columns)

Numerical dtype columns: ['SeniorCitizen', 'tenure', 'MonthlyCharges']

Categorical/text dtype columns: ['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn']

Date/time dtype columns: []

Potential identifier columns: ['customerID']

Potential target columns: ['Churn']

### Output explanation
The lists group columns using their current pandas dtypes and a few name-based candidates. Name-based detection is only a heuristic.
Some fields need manual review. Numeric codes may represent categories, dates may be stored as text, and an identifier may not follow a standard naming convention.

### AI/ML relevance
Correctly identifying column roles helps determine what to inspect next and prevents unsuitable columns from being treated as ordinary numeric features.

## Final Inspection Summary

### Code
Build a compact report from the checks above.

In [22]:
inspection_summary = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Duplicate rows (exact)",
        "Missing cells recognized by pandas",
        "Numerical dtype columns",
        "Categorical/text dtype columns",
        "Date/time dtype columns",
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        int(df.duplicated().sum()),
        int(df.isna().sum().sum()),
        len(numeric_columns),
        len(categorical_columns),
        len(datetime_columns),
    ],
})
display(inspection_summary)

                               Metric  Value
0                                Rows   7043
1                             Columns     21
2              Duplicate rows (exact)      0
3  Missing cells recognized by pandas      0
4             Numerical dtype columns      3
5      Categorical/text dtype columns     18
6             Date/time dtype columns      0